# -*- coding: utf-8 -*-
"""Marketing - Recomendador de Campanhas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGkbkzZbBbkOUum0OgOm2US4sK0isnGU
"""

import pandas as pd
import numpy as np
from sklearn.decomposition import NMF
import warnings
from io import StringIO

# Suprimir warnings de convergência do NMF
warnings.filterwarnings('ignore')

# Dados da matriz fornecida na imagem, agora com os nomes dos clientes
dados_avaliacao_str = """
Cliente,Campanha_A,Campanha_B,Campanha_C,Campanha_D,Campanha_E
João,5,4,NaN,1,NaN
Maria,NaN,5,4,3,5
Pedro,1,NaN,5,4,2
Ana,5,4,NaN,NaN,4
Carlos,NaN,1,3,5,NaN
Paula,4,5,NaN,1,NaN
Rafael,1,NaN,5,4,3
Sofia,5,NaN,NaN,5,5
"""
df_avaliacao = pd.read_csv(StringIO(dados_avaliacao_str), index_col='Cliente')

# Mapeamento dos Nomes de Marketing
mapeamento_nomes = {
    'Campanha_A': 'Conecte-se Mais',
    'Campanha_B': 'Cashback Surpresa',
    'Campanha_C': 'Frete Grátis',
    'Campanha_D': 'Aprende e Ganha',
    'Campanha_E': 'Pré Venda Exclusiva'
}

print("--- Matriz Original de Avaliações (Nomes Corretos) ---")
print(df_avaliacao)

# Pré-processamento: Preencher NaN com 0 para o modelo de Fatoração
R = df_avaliacao.fillna(0).values

# --- TREINAMENTO E PREVISÃO COM NMF ---
n_fatores = 3
model_nmf = NMF(n_components=n_fatores, init='random', random_state=42, max_iter=500)
model_nmf.fit(R)

# Reconstruir a Matriz (Previsão)
R_previsto = model_nmf.transform(R) @ model_nmf.components_

df_previsao = pd.DataFrame(R_previsto, index=df_avaliacao.index, columns=df_avaliacao.columns)
df_previsao = df_previsao.clip(lower=1, upper=5)

print("\n--- Matriz de Avaliações Previsão (Notas Faltantes Preenchidas) ---")
print(df_previsao.round(2))

# --- GERAÇÃO DA RECOMENDAÇÃO FINAL ---
def recomendar_campanha(cliente_id, df_original, df_previsto):
    """Identifica a campanha não vista com a maior nota prevista para o cliente."""
    avaliacoes_existentes = df_original.loc[cliente_id].dropna().index
    campanhas_nao_vistas = df_previsto.columns.difference(avaliacoes_existentes)

    if campanhas_nao_vistas.empty:
        return "Nenhuma campanha restante para recomendar.", 0

    previsoes_nao_vistas = df_previsto.loc[cliente_id, campanhas_nao_vistas]
    melhor_campanha = previsoes_nao_vistas.idxmax()
    nota_prevista = previsoes_nao_vistas.max()

    return melhor_campanha, nota_prevista

# Executar a recomendação para todos os clientes
resultados_recomendacao = {}
for cliente in df_avaliacao.index:
    campanha, nota = recomendar_campanha(cliente, df_avaliacao, df_previsao)
    resultados_recomendacao[cliente] = {'Campanha Recomendada': campanha, 'Nota Prevista': nota}

df_recomendacoes = pd.DataFrame(resultados_recomendacao).T

# Aplica o mapeamento dos Nomes de Marketing
df_final = df_recomendacoes.copy()
df_final['Campanha Recomendada'] = df_final['Campanha Recomendada'].replace(mapeamento_nomes)

print("\n--- RECOMENDAÇÃO FINAL PERSONALIZADA (8 CLIENTES) ---")
print(df_final)